# Generated by Django 3.0.5 on 2025-05-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('traditional_pottery', 'Traditional Pottery'), ('indigenous_jewelry', 'Indigenous Jewelry'), ('home_decor', 'Home Decor'), ('textiles', 'Textiles'), ('wearables_bags', 'Wearables & Bags'), ('souvenirs', 'Souvenirs'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
